### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by zbelial** [thierryvolpiatto/psession#11]
when starting up, emacs reports an error about psession, the backtrace is as follow:
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  window-state-put(nil nil safe)
  psession--restore-winconf-1("last_session5247" nil safe)
  #f(compiled-function () #<bytecode 0x2202669>)()
  apply(#f(compiled-function () #<bytecode 0x2202669>) nil)
  timer-event-handler([t 0 0 10000 nil #f(compiled-function () #<bytecode 0x2202669>) nil idle 0])
```

It seems that psession tries to load something that doesn't exist, but I don't have enough knowledge to figure out the problem now.

And below is my config( I'm using emacs 26.1 on Manjaro)
```elisp
(use-package psession
  ;; :disabled t
  :config (progn
            (setq psession-object-to-save-alist
				  (quote
					((helm-apropos-history . "helm-apropos-history.el")
					 (minibuffer-history . "minibuffer-history.el")
					 (extended-command-history . "extended-command-history.el")
					 (helm-external-command-history . "helm-external-command-history.el")
					 ;; (helm-surfraw-engines-history . "helm-surfraw-engines-history.el")
					 (psession--save-buffers-alist . "psession-save-buffers-alist.el")
					 ;; (helm-ff-history . "helm-ff-history.el")
					 ;; (regexp-search-ring . "regexp-search-ring.el")
					 ;; (search-ring . "search-ring.el")
					 ;; (file-name-history . "file-name-history.el")
					 (kill-ring . "kill-ring.el")
					 ;; (kill-ring-yank-pointer . "kill-ring-yank-pointer.el")
					 ;; (register-alist . "register-alist.el")
					 ;; (psession--winconf-alist . "psession-winconf-alist.el")
					 )))
            (psession-mode 1)
            (psession-savehist-mode 1)
            )
  )
```

**Comment by zbelial** [comment]
Forgot to mention that both v1.5 and lastest master code have this problem for me.

**Comment by thierryvolpiatto** [comment]
太阳 <notifications@github.com> writes:

> when starting up, emacs reports an error about psession, the backtrace is as follow:
>
> Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
>   window-state-put(nil nil safe)
>   psession--restore-winconf-1("last_session5247" nil safe)
>   #f(compiled-function () #<bytecode 0x2202669>)()
>   apply(#f(compiled-function () #<bytecode 0x2202669>) nil)
>   timer-event-handler([t 0 0 10000 nil #f(compiled-function () #<bytecode 0x2202669>) nil idle 0])
>
> It seems that psession tries to load something that doesn't exist, but
> I don't have enough knowledge to figure out the problem now.

Try to delete psession-winconf-alist.elc file and restart emacs.

--
Thierry

**Comment by zbelial** [comment]
Sadly it doesn't work. It's wired that this problem only happens in one of my computers.  I think I should spend some time to figure out the problem. Thanks anyway.
I'll post another comment to report the result, so please keep this issue open now.

**Comment by thierryvolpiatto** [comment]
I am still unable to reproduce this bug.
BTW what is the value of `psession--winconf-alist`?
Also can you use once emacs is started, `psession-save-winconf`, change your window layout and use `psession-restore-winconf` to restore previous state?
Do you have errors?

**Comment by zbelial** [comment]
I made another test, and here is the result.
I ignored the error that I reported in previous post and invoked `psession-save-winconf`,  then the value of `psession--winconf-alist` was : 
```elisp
(("*GNU Emacs*"
  ((min-height . 4)
   (min-width . 10)
   (min-height-ignore . 2)
   (min-width-ignore . 6)
   (min-height-safe . 1)
   (min-width-safe . 2)
   (min-pixel-height . 92)
   (min-pixel-width . 80)
   (min-pixel-height-ignore . 46)
   (min-pixel-width-ignore . 48)
   (min-pixel-height-safe . 23)
   (min-pixel-width-safe . 16))
  leaf
  (pixel-width . 1867)
  (pixel-height . 906)
  (total-width . 233)
  (total-height . 39)
  (normal-height . 1.0)
  (normal-width . 1.0)
  (buffer "*GNU Emacs*"
	  (selected . t)
	  (hscroll . 0)
	  (fringes 8 8 nil)
	  (margins nil)
	  (scroll-bars nil 2 t nil 0 t)
	  (vscroll . 0)
	  (dedicated)
	  (point . 77)
	  (start . 1))))
```
after doing that I split the window using `C-x 2` and then invoked `psession-restore-winconf`,  previous window state was restored successfully.
During this test, there was no error.

**Comment by thierryvolpiatto** [comment]
太阳 <notifications@github.com> writes:

> Hi
> I have a question, psession only save files in directory 'psession-elisp-objects-default-directory', right?
> The reason why I ask this question is that I wanted to make some tests as you suggested so I deleted all files in directory 'psession-elisp-objects-default-directory' and started emacs using the same config(same psession version) as
> before, but then emacs reported some error, which is as following
>
> Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
>   window-state-put(nil nil safe)
>   (progn (select-frame (last-nonminibuffer-frame) 'norecord) (delete-other-windows) (window-state-put (cdr (assoc conf psession--winconf-alist)) window ignore))
>   (unwind-protect (progn (select-frame (last-nonminibuffer-frame) 'norecord) (delete-other-windows) (window-state-put (cdr (assoc conf psession--winconf-alist)) window ignore)) (if (frame-live-p old-frame) (progn (select-frame old-frame 'norecord))) (if (buffer-live-p old-buffer) (progn (set-buffer old-buffer))))
>   (let ((old-frame (selected-frame)) (old-buffer (current-buffer))) (unwind-protect (progn (select-frame (last-nonminibuffer-frame) 'norecord) (delete-other-windows) (window-state-put (cdr (assoc conf psession--winconf-alist)) window ignore)) (if (frame-live-p old-frame) (progn (select-frame old-frame 'norecord))) (if (buffer-live-p old-buffer) (progn (set-buffer old-buffer)))))
>   psession--restore-winconf-1("last_session5247" nil safe)
>   (closure (dired-buffers t) nil (psession--restore-winconf-1 psession--last-winconf nil 'safe))()
>   apply((closure (dired-buffers t) nil (psession--restore-winconf-1 psession--last-winconf nil 'safe)) nil)
>   timer-event-handler([t 0 0 10000 nil (closure (dired-buffers t) nil (psession--restore-winconf-1 psession--last-winconf nil 'safe)) nil idle 0])
>
> What should I do to test psession from a fresh state? Thanks. And thanks very much for helping me figure out this problem.

Sorry for late reply.  Psession is build to be used from emacs, so the
first time you use it, it is assumed you start psession-mode from within
emacs (M-x psession-mode), then you add (psession-mode 1) to your init
file, you restart emacs and the last used window configuration is
restored.  Once this done, if you delete files from
psession-elisp-objects-default-directory from outside emacs, you have
obviously an error.

I made a change for failing safely with window configuration, I will
soon make some more changes to handle this scenario.

Thanks.

--
Thierry

**Comment by zbelial** [comment]
Ok, I got it.
And thanks again for creating this very useful package. I'll close this issue then.
