### ISSUE TITLE
no-littering support

### ISSUE THREAD

**Issue by manuel-uberti** [thierryvolpiatto/psession#12]
Hi,

first of all thanks for this package, and for Helm as well. I have probably thanked you already, but your efforts are fantastic.

I am trying to add support for `psession` in `no-littering`. I opened a PR here: https://github.com/emacscollective/no-littering/pull/109

Do you think it makes sense to create a `psession` directory? I guess this is what @tarsius is asking for. :)

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> Hi,
>
> first of all thanks for this package, and for Helm as well. I have probably thanked you already, but your efforts are fantastic.

Thanks.

> I am trying to add support for psession in no-littering. I opened a PR here: emacscollective/no-littering#109
>
> Do you think it makes sense to create a psession directory? I guess this is what @tarsius is asking for. :)

Well, psession already create a directory at "~/.emacs.d/elisp-objects/"
by default, this is configurable with
`psession-elisp-objects-default-directory`, isn't this enough?

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
Thanks for the quick reply.

> Well, psession already create a directory at "~/.emacs.d/elisp-objects/" by default, this is configurable with `psession-elisp-objects-default-directory`, isn't this enough?

I think so. Or, to phrase it better, I tried to follow the `no-littering` conventions in my PR, so maybe it's me getting it wrong. Let's hope @tarsius can tell us more, then.

**Comment by thierryvolpiatto** [comment]
After reading the no-littering home page, perhaps what you want is:

```elisp
(setq psession-elisp-objects-default-directory (expand-file-name "psession/" no-littering-var-directory))
```

**Comment by manuel-uberti** [comment]
Thank you!

I updated the PR. Can I keep this open until it is merged? Just so we can check with @tarsius is anything else needs to be done.

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> Thank you!
>
> I updated the PR. Can I keep this open until it is merged?

Sure!

> Just so we can check with @tarsius is anything else needs to be done.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
PR got merged. Thanks again for the support.
