### ISSUE TITLE
emacs 27.1: psession fails to save `register-alist` when there is a marker in it

### ISSUE THREAD

**Issue by slippycheeze** [thierryvolpiatto/psession#16]
psession fails to save `register-alist` if there is a marker in it.  

To reproduce:

1. hit `C-x r SPACE`, or otherwise run `point-to-register`.
2. save the `register-alist` object with psession, in any way you please.

alternatively, you can run: 
```elisp
(let ((data (list (const 97 (point-marker)))))
  (debug)
  (psession--dump-object-save-register-alist data))
```

The printed version of `register-alist` with a marker is `((97 . #<marker at 182 in *scratch*>))`; Since `#<` is (deliberately) invalid read syntax this ends up breaking during saving the objects.

The simple work-around would be to omit markers from the object.  That avoids the problem that they have no readable form.

The full fix would, sadly, involves a little custom processing to rebuild a marker, and a little of the structure of the code makes that more difficult.  A demonstration version without much error handling (though roughly correct) would be:

```elisp
(progn
  (defun serialize-marker (marker)
    "Create a readable version of MARKER."
    `(when-let ((buffer (get-buffer ,(buffer-name (marker-buffer marker))))
                (restored-marker (make-marker)))
       (set-marker restored-marker ,(marker-position marker) buffer)
       (set-marker-insertion-type restored-marker ,(marker-insertion-type marker))
       restored-marker))

  (debug)
  (eval
   (car-safe
    (read-from-string
     (prin1-to-string
      (serialize-marker (point-marker)))))))
```

Unfortunately this won't trivially integrated, for two reasons:
1. `psession--dump-object-to-file` assumes that it will `prin1` an object with the save name as value, and
2. if you `eval-when-compile` that code it'll generate the wrong thing, so it needs to bypass that logic.

It'd be very nice to have this supported, and I might see about some sort of patch to do it later, but for now I've just removed the `register-alist` from the default set of things to save.

**Comment by thierryvolpiatto** [comment]
Daniel Pittman <notifications@github.com> writes:

> psession fails to save register-alist if there is a marker in it.

Normally `psession--dump-object-save-register-alist` should exclude
unprintable objects like marker.

> To reproduce:
>
>  1. hit C-x r SPACE, or otherwise run point-to-register.
>  2. save the register-alist object with psession, in any way you please.

For now I couldn't reproduce, I will try again ASAP.

> alternatively, you can run:
>
> (let ((data (list (const 97 (point-marker)))))
>   (debug)
>   (psession--dump-object-save-register-alist data))

`psession--dump-object-save-register-alist` takes a file as argument.

> The printed version of register-alist with a marker is ((97 . #<marker
> at 182 in *scratch*>)); Since #< is (deliberately) invalid read syntax
> this ends up breaking during saving the objects.

Yes of course.

> The simple work-around would be to omit markers from the object. That
> avoids the problem that they have no readable form.

It is what we are doing actually.

> The full fix would, sadly, involves a little custom processing to
> rebuild a marker, and a little of the structure of the code makes that
> more difficult.

No I don't want to go this way, I want to keep things simple.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Daniel Pittman <notifications@github.com> writes:

> psession fails to save register-alist if there is a marker in it.
>
> To reproduce:
>
>  1. hit C-x r SPACE, or otherwise run point-to-register.
>  2. save the register-alist object with psession, in any way you please.

No, I can't reproduce, psession is excluding this register properly.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
This with Emacs-28, I will try later with another Emacs.

**Comment by thierryvolpiatto** [comment]
Maybe try to close Emacs, delete register-alist.elc from command line, start Emacs, save some registers and restart Emacs.

**Comment by slippycheeze** [comment]
Huh.  I'll investigate further, and see if I can figure out what is going wrong.  -__-
