### ISSUE TITLE
Difference with desktop.el

### ISSUE THREAD

**Issue by azzamsa** [thierryvolpiatto/psession#9]
I shared this package in [r/emacs](https://www.reddit.com/r/emacs/comments/8dlytl/yet_another_package_for_emacs_persistent_sessions/)

Reading their comments suggest this project to have short description of differences with desktop.el

Thanks.

**Comment by thierryvolpiatto** [comment]
azzamsa <notifications@github.com> writes:

> I shared this package in r/emacs
>
> Reading their comments suggest this project to have short description
> of differences with desktop.el

I know the people who commented there and they will never use psession,
short description or not :-) so I don't care much.

Isn't the description in README clear enough? 

-- 
Thierry

**Comment by azzamsa** [comment]
> I know the people who commented there and they will never use psession, short description or not :-) so I don't care much.

:)

> By the way, after the release of version 3.0 I will have to stop
developing Helm seriously until I get enough financial support,
only providing a minimal bugfix maintenance.
Thanks for your understanding

Very sad to read this. I read lot of way to sustain FOSS work including [this](https://github.com/nayafia/lemonade-stand) article. 

I use helm all the time. more more productive with it. This is the only package that make my jaw dropped. Really great packages. I never know those features exist. I have a plan to cover what tuhdo didn't in his helm intro.

Thank lot for this great package. If only I have a job. Donation will be my obligation.

*Sorry to write it here. I hope other realize that we can't take FOSS work for granted*

**Comment by thierryvolpiatto** [comment]
azzamsa <notifications@github.com> writes:

> Very sad to read this.



> I read lot of way to sustain FOSS work including this article.

Thanks for the link, very interesting.

> I use helm all the time. more more productive with it. This is the
> only package that make my jaw dropped. Really great packages. I never
> know those features exist. I have a plan to cover what tuhdo didn't in
> his helm intro.
>
> Thank lot for this great package. If only I have a job. Donation will be my obligation.
>
> Sorry to write it here. I hope other realize that we can't take FOSS work for granted

Thanks for your interest and support for helm and my other packages like
this one ;-)

--
Thierry

**Comment by azzamsa** [comment]
Sure. Your effort never lies.
![2018-05-07-13 09 45](https://user-images.githubusercontent.com/17734314/39687302-f23986d8-51f7-11e8-8ace-633f4aca50e7.png)


I believe many people benefit from Helm out there. Many project succeeded in asking donation. e.g [Quicklisp](https://twitter.com/quicklisp/status/806914603510706176), [magit](https://github.com/magit/magit/blob/master/Documentation/BACKERS.md). I belive Helm will get there.
